### ISSUE TITLE
Console warnings

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#1083]
These can be seen here:

https://github.com/FAIRsharing/fairsharing.github.io/pull/1082/checks?check_run_id=2873797676

Summary:

```
PASS tests/unit/store/users.spec.js
(node:1999) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1999) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:1999) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
PASS tests/unit/components/Records/Record/Support.spec.js
(node:1999) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'querySelector' of null
(node:1999) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 23)
```

These will need to be handled in users.js and Support.vue.

**Comment by knirirr** [comment]
A more detailed trace can be found here:

https://github.com/FAIRsharing/fairsharing.github.io/pull/1086/checks?check_run_id=2876726094

Using:

https://github.com/grantila/trace-unhandled#in-unit-tests

```
PASS tests/unit/store/users.spec.js

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "(node:2019) UnhandledPromiseRejectionWarning
    TypeError: Cannot read property 'data' of undefined
        at VueComponent.checkClaimStatus (/home/runner/work/fairsharing.github.io/fairsharing.github.io/src/views/Records/Record.vue:5655:38)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at VueComponent.<anonymous> (/home/runner/work/fairsharing.github.io/fairsharing.github.io/src/views/Records/Record.vue:5532:9)".



      at VueComponent.checkClaimStatus (src/views/Records/Record.vue:5655:38)
      at VueComponent.<anonymous> (src/views/Records/Record.vue:5532:9)".
      at console.error (node_modules/@jest/console/build/BufferedConsole.js:163:10)
      at defaultLogger (node_modules/trace-unhandled/dist/lib/core.js:44:13)
      at Object.logger (node_modules/trace-unhandled/dist/lib/core.js:58:5)
      at process.<anonymous> (node_modules/trace-unhandled/dist/lib/register.js:5:12)

```

```
PASS tests/unit/components/Records/Record/Support.spec.js

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "(node:2019) UnhandledPromiseRejectionWarning
    TypeError: Cannot read property 'querySelector' of null
        at Object.$ (/home/runner/work/fairsharing.github.io/fairsharing.github.io/node_modules/vue-scrollto/vue-scrollto.js:180:23)
        at VueComponent.scrollTo [as $scrollTo] (/home/runner/work/fairsharing.github.io/fairsharing.github.io/node_modules/vue-scrollto/vue-scrollto.js:387:19)
        at VueComponent.<anonymous> (/home/runner/work/fairsharing.github.io/fairsharing.github.io/src/views/Records/Records.vue:2414:14)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)".



      at Object.$ (node_modules/vue-scrollto/vue-scrollto.js:180:23)
      at VueComponent.scrollTo [as $scrollTo] (node_modules/vue-scrollto/vue-scrollto.js:387:19)
      at VueComponent.<anonymous> (src/views/Records/Records.vue:2414:14)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)".
      at console.error (node_modules/@jest/console/build/BufferedConsole.js:163:10)
      at defaultLogger (node_modules/trace-unhandled/dist/lib/core.js:44:13)
      at Object.logger (node_modules/trace-unhandled/dist/lib/core.js:58:5)
      at process.<anonymous> (node_modules/trace-unhandled/dist/lib/register.js:5:12)
```

```
