### ISSUE TITLE
Console error in tests

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#1747]
This has started appearing:

```
console.error node_modules/jest-environment-jsdom-fifteen/node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Error: connect ECONNREFUSED 127.0.0.1:3000
        at Object.dispatchError (/Users/milo/Work/Web/fairsharing.github.io/node_modules/jest-environment-jsdom-fifteen/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:54:19)
        at EventEmitter.<anonymous> (/Users/milo/Work/Web/fairsharing.github.io/node_modules/jest-environment-jsdom-fifteen/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:675:20)
        at EventEmitter.emit (events.js:412:35)
        at Request.<anonymous> (/Users/milo/Work/Web/fairsharing.github.io/node_modules/jest-environment-jsdom-fifteen/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:384:47)
        at Request.emit (events.js:400:28)
        at Request.onRequestError (/Users/milo/Work/Web/fairsharing.github.io/node_modules/request/request.js:877:8)
        at ClientRequest.emit (events.js:400:28)
        at Socket.socketErrorListener (_http_client.js:475:9)
        at Socket.emit (events.js:400:28)
        at emitErrorNT (internal/streams/destroy.js:106:8)
        at emitErrorCloseNT (internal/streams/destroy.js:74:3)
        at processTicksAndRejections (internal/process/task_queues.js:82:21) undefined
```

Spotted for:

tests/unit/store/records.spec.js
tests/unit/views/Organisations/Organisation.spec.js
tests/unit/views/Users/EditPublicProfile.spec.js

**Comment by knirirr** [comment]
This has disappeared again...
